version: "3"

services:
  manhattan_php:
    build:
      context: .
      dockerfile: ./etc/docker/Dockerfile
    container_name: manhattan-php

    volumes:
      - ./:/var/www/html/

  manhattan_pgsql:
    image: postgres:11
    container_name: manhattan-psql
    restart: always
    environment:
      - POSTGRES_DB=i-am-your-father
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
    volumes:
      - ./etc/docker/postgres/:/docker-entrypoint-initdb.d/

  manhattan_nginx:
    image: nginx:latest
    container_name: manhattan-nginx
    ports:
      - "8444:80"
    volumes:
      - ./:/var/www/html/
      - ./etc/docker/nginx/manhattan.conf:/etc/nginx/conf.d/default.conf
    links:
      - manhattan_php
    depends_on:
      - manhattan_php
      - manhattan_pgsql
