version: "3"

services:
  php:
    container_name: garciasdos_php
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./etc/docker/Dockerfile
    volumes:
      - ./:/var/www/powernav

  postgres:
    container_name: garciasdos_postgres
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_DB=manhattan
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - 5455:5432

  nginx:
    container_name: garciasdos_nginx
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - "81:80"
    volumes:
      - ./:/var/www/powernav
      - ./etc/docker/nginx/manhattan.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    depends_on:
      - php
      - postgres
