<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGStSwE8\PowerNav_Apps_Backend_PowerNavBackendKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGStSwE8/PowerNav_Apps_Backend_PowerNavBackendKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGStSwE8.legacy');

    return;
}

if (!\class_exists(PowerNav_Apps_Backend_PowerNavBackendKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGStSwE8\PowerNav_Apps_Backend_PowerNavBackendKernelDevDebugContainer::class, PowerNav_Apps_Backend_PowerNavBackendKernelDevDebugContainer::class, false);
}

return new \ContainerGStSwE8\PowerNav_Apps_Backend_PowerNavBackendKernelDevDebugContainer([
    'container.build_hash' => 'GStSwE8',
    'container.build_id' => 'e69da067',
    'container.build_time' => 1590925146,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGStSwE8');
