<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'sets_get' => [[], ['_controller' => 'PowerNav\\Apps\\Backend\\Controller\\Set\\SetController'], [], [['text', '/sets']], [], []],
];
